apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
  name: ing-web
  namespace: default
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: web-flask
          servicePort: 7777
        path: /
