kind: PersistentVolume
apiVersion: v1
metadata:
  name: prom-server-volume
  labels:
    type: local
spec:
  storageClassName: prom-server
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prom-server/"
