kind: PersistentVolume
apiVersion: v1
metadata:
  name: graf-server-volume
  labels:
    type: local
spec:
  storageClassName: graf-server
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/graf-server/"
